services:
  api:
    build:
      context: .
      dockerfile: EvChargeSystem.Api/Dockerfile
    container_name: evcharge-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Server=sqlserver,1433;Database=EvChargeDb;User Id=sa;Password=Your_password123;TrustServerCertificate=True
      RabbitMq__Host: rabbitmq
      RabbitMq__Port: 5672
      RabbitMq__UserName: guest
      RabbitMq__Password: guest
      RabbitMq__Exchange: charging.events
      RabbitMq__Queue: charging.workflow.queue
      Seed__DemoUserName: demo
      Seed__DemoApiKey: demo-api-key-12345
    depends_on:
      sqlserver:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: evcharge-sqlserver
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: Your_password123
    ports:
      - "1433:1433"
    volumes:
      - sql_data:/var/opt/mssql
    healthcheck:
      test: ["CMD-SHELL", "(/opt/mssql-tools18/bin/sqlcmd -C -S localhost -U sa -P Your_password123 -Q \"SELECT 1\") || (/opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P Your_password123 -Q \"SELECT 1\")"]
      interval: 10s
      timeout: 5s
      retries: 20
      start_period: 20s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: evcharge-rabbitmq
    restart: unless-stopped
    ports:
      - "5673:5672"
      - "15673:15672"
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "ping"]
      interval: 10s
      timeout: 5s
      retries: 15
      start_period: 15s

volumes:
  sql_data:
